### ISSUE TITLE
How to view the output 

### ISSUE THREAD

**Issue by fayiz7** [BlockbirdLabs/blocksim#9]
Hi Carlos

First of all , I appreciate your contribution in writing this blockchain simulator.
I am wondering how to view the result?
I did all the steps you've mentioned and successfully ran the simulation. This the last lines:
```sh
tokyo-3 at 09-30 17:01:03: New blocks received {'c565308980fb65d224b410e71446da4a62c54ea4b72a3d53b729d747644f94d4': 228}
tokyo-3 at 09-30 17:01:03: Message (ID: get_headers) sent with 5.4e-05 MB with a destination: tokyo-2
tokyo-2 at 09-30 17:01:03: Receive a message (ID: get_headers) created at 09-30 17:01:03 from tokyo-1
tokyo-2 at 09-30 17:01:03: 1 Block header(s) preapred to send
tokyo-2 at 09-30 17:01:03: Receive a message (ID: get_headers) created at 09-30 17:01:03 from tokyo-3
tokyo-2 at 09-30 17:01:03: 1 Block header(s) preapred to send
```

So, is the the output ? in text only?
I saw a jason file called report but don't know how to open it?
Can you please guide me in this issue?

Many thanks in advance
Fayiz Alsubaie

**Comment by carlosfaria94** [comment]
Hi @fayiz7 
The only way to see the simulation events is only by text.

The reports in json can be viewed in any text editor, and they will show relevant metrics about the simulation.

**Comment by fayiz7** [comment]
Thank a lot @carlosfaria94
